select I.ITEMNAME,I.ITEMCODE,I.BRAND,
I.CATEGORY1,
sum(OD.AMOUNT) TOTALAMOUNT,SUM(OD.LINETOTAL) TOTALPRICE,
MIN(OD.UNITPRICE) MINPRICE,MAX(OD.UNITPRICE) MAXPRICE,
AVG(OD.UNITPRICE) AVGPRICE
FROM
ITEMS I 
JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID

GROUP BY I.ITEMNAME,I.ITEMCODE,I.BRAND,
I.CATEGORY1

-- toplam kaç ürün hangi fiyattansatýlmýs


--ORNEK 1

SELECT * FROM ITEMS
WHERE ITEMCODE='10000' 




SELECT I.ID, I.ITEMNAME,I.ITEMCODE,I.BRAND,
I.CATEGORY1
FROM ITEMS I
WHERE ITEMCODE='35577' 



/*

SELECT

I.1D,I.ITEMCODE , I. ITEMNAME , I. BRAND, I. CATEGORY1

(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOTALAMOUNT,
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOTALSALE
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID) MINPRICE,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID) MAXPRICE

(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID) AVGPRICE
FROM ITEMS I


*/
