select U.ID,U.NAMESURNAME

from USERS U
WHERE ID=1
SELECT * FROM ADDRESS WHERE USERID=1

select TOP 1 
O.DATE_,A.ADDRESSTEXT from ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE O.USERID=1
order by O.DATE_ DESC
