-- GROUPBY ALISTIRMALAR1
-- gun bazli satis rakami


SELECT * FROM SALES

where CITY='ÝSTANBUL'



-- Yazim bu sekilde olucak-SAATLERDEN KURTULDUM
SELECT 
CONVERT(date,DATE_) as tarih ,sum(TOTALPRICE) as toplamciro
FROM SALES 
WHERE CITY='ÝSTANBUL'

group by CONVERT(date,DATE_)
order by 1

--orderbyda alias kullanabiliyoruz
SELECT 
CONVERT(date,DATE_) as tarih ,sum(TOTALPRICE) as toplamciro
FROM SALES 
WHERE CITY='ÝSTANBUL'

group by CONVERT(date,DATE_)
order by tarih

--alýstýrma 2: BÝR GUNUN MAGAZA SATISI

-- 2019 yýlý subat satislari
select * from SALES 

WHERE CONVERT(date,DATE_)='2019-02-12'


--between kullanim

 

SELECT
CITY,SUM(TOTALPRICE) AS TOTALSALE

FROM SALES

WHERE DATE_ BETWEEN '2019-04-23 00:00:00' AND '2019-04-23 23:59:59'
GROUP BY CITY
ORDER BY 2 DESC


-- ORDER BY ALIAS

SELECT
CITY,SUM(TOTALPRICE) AS TOTALSALE

FROM SALES

WHERE DATE_ BETWEEN '2019-04-23 00:00:00' AND '2019-04-23 23:59:59'
GROUP BY CITY
ORDER BY TOTALSALE DESC

SELECT TOP 5
CITY,SUM(TOTALPRICE) AS TOTALSALE

FROM SALES

WHERE DATE_ BETWEEN '2019-04-23 00:00:00' AND '2019-04-23 23:59:59'
GROUP BY CITY
ORDER BY 2 DESC
