select count (ID) from SALES
where CITY='ANTALYA'

select count (*) as satýrsayisi ,SUM(TOTALPRICE),AVG(TOTALPRICE) ortalama_birim_Satis,max(TOTALPRICE) en_yuksek_fiyat from SALES
where CITY='ANTALYA'
-- groupby 
select  * from SALES
 
 --
SELECT 
COUNT(*) SATIRSAYISI,
SUM(TOTALPRICE) TOPLAMCIRO,AVG(TOTALPRICE) ORTALAMA_BIRIM_SATIS_TUTARI,
MIN(TOTALPRICE ) ENDUSUKFIYAT,
MAX(TOTALPRICE) ENYUKSEKFIYAT
FROM SALES
WHERE CITY IN ('ÝSTANBUL','ANTALYA') 
-- ÝSTANBUL ANKARA OLUP BOYLE OLANLARI DÖNDÜK


SELECT CITY,
COUNT(*) SATIRSAYISI,
SUM(TOTALPRICE) TOPLAMCIRO,AVG(TOTALPRICE) ORTALAMA_BIRIM_SATIS_TUTARI,
MIN(TOTALPRICE ) ENDUSUKFIYAT,
MAX(TOTALPRICE) ENYUKSEKFIYAT
FROM SALES
WHERE CITY IN ('ÝSTANBUL','ANTALYA') -- 5 agg kullanmisiz city agg degil onu da dahil etmeliyiz

group by CITY
-- 2.ornek: her bir magazanin ilcelerindeki musterilere ne kadar satýþ yaptýgý
SELECT

CITY,DISTRICT ,

COUNT(*) SATIRSAYISI,

SUM(TOTALPRICE) TOPLAMCIRO,AVG(TOTALPRICE) ORTALAMA_BIRIM_SATIS_TUTARI,
MIN(TOTALPRICE) ENDUSUKFIYAT,

MAX(TOTALPRICE) ENYUKSEKFIYAT

FROM SALES

GROUP BY CITY, DISTRICT
-- ilce kýrýlýmýnda satýs sayisi max min 


select * FROM SALES


-- CATEGORY KIRILIMINDA QUERY



SELECT
  CATEGORY1,
  CATEGORY2,
  COUNT(*) AS SATIRSAYISI,
  SUM(TOTALPRICE) AS TOPLAMCIRO,
  AVG(TOTALPRICE) AS ORTALAMA_BIRIM_SATIS_TUTARI,
  MIN(TOTALPRICE) AS ENDUSUKFIYAT,
  MAX(TOTALPRICE) AS ENYUKSEKFIYAT
FROM
  SALES
GROUP BY
  CATEGORY1, CATEGORY2
ORDER BY
  CATEGORY1, CATEGORY2;



  SELECT
  CATEGORY1,
  COUNT(*) AS SATIRSAYISI,
  SUM(TOTALPRICE) AS TOPLAMCIRO,
  AVG(TOTALPRICE) AS ORTALAMA_BIRIM_SATIS_TUTARI,
  MIN(TOTALPRICE) AS ENDUSUKFIYAT,
  MAX(TOTALPRICE) AS ENYUKSEKFIYAT
FROM
  SALES
GROUP BY
  CATEGORY1
ORDER BY
  CATEGORY1
