select U.USERNAME_,U.NAMESURNAME,A.POSTALCODE,A.ADDRESSTEXT,C.COUNTRY,CT.CITY,DS.DISTRICT
from USERS U --alias
JOIN ADDRESS A on U.ID=A.USERID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
ORDER BY U.USERNAME_
--BÝRDEN FAZLA TABLO EKLEMEK ÝÇÝN JOÝN YAZIP ÝLERLÝYORUZ
-- 4 satir bir kullanýci 4 adresi var


--ORDER ORDER DETAILS,ITEMS TABLOLARI

select * from ORDERS

WHERE ID=1
select * from ORDERDETAILS WHERE ORDERID=1

select  * from ITEMS where ID=660 --DOKME KIMYON 10 KG. 
SELECT * FROM ITEMS WHERE ID=1673 --SILA TRUVA 1 NO CAYDANLIK
-- ORDER TABOSUNDAKÝ ID = 1 CAGRILDI USER ID = 7678

SELECT * 
FROM USERS WHERE
ID=7678

SELECT * FROM ADDRESS WHERE ID=18770
