select * from ORDERS WHERE ID=1

select * from INVOICES WHERE ORDERID=1
--2019-02-05 23:56:58.000
--2019-02-06 10:54:58.000

-- FARKA BAKARSAK

SELECT DATEDIFF(HOUR,'2019-02-05 23:56:58.000','2019-02-06 10:54:58.000')

-- ÝKÝSÝNÝ BAGLAYALIM

SELECT O.ID,O.DATE_ ORDERDATE_,I.DATE_ INVOICEDATE
FROM ORDERS O
JOIN INVOICES I ON O.ID=I.ORDERID


SELECT O.ID,O.DATE_ ORDERDATE_,I.DATE_ INVOICEDATE,
DATEDIFF(DAY,O.DATE_,I.DATE_) FARK
FROM ORDERS O
JOIN INVOICES I ON O.ID=I.ORDERID


--HANGÝ SEHRE ORTALAMA NE KADAR HAZIRLIK YAPABÝLÝYORUZ?
SELECT C.CITY SEHIR, AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) FARK
FROM ORDERS O
JOIN INVOICES I ON O.ID=I.ORDERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY
ORDER BY 2 DESC
---
SELECT C.CITY FROM ORDERS
JOIN ADDRESS A ON A.ID=ORDERS.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID