--ORDER UZERINDEN

SELECT O.ID,O.TOTALPRICE,O.DATE_,I.ITEMCODE,I.ITEMNAME,
I.BRAND,I.CATEGORY1,I.CATEGORY2,OD.LINETOTAL,OD.UNITPRICE,U.USERNAME_,
U.NAMESURNAME,A.ADDRESSTEXT,CT.CITY,DS.DISTRICT

FROM ORDERS O 

JOIN ORDERDETAILS OD ON  OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A  ON A.ID=A.USERID
JOIN CITIES CT ON  CT.ID=A.CITYID
JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
WHERE O.ID=1